Fix coding style issue in Debian init script

diff --git a/templates/etc/init.d/deb/td-agent b/templates/etc/init.d/deb/td-agent
--- a/templates/etc/init.d/deb/td-agent
+++ b/templates/etc/init.d/deb/td-agent
@@ -39,28 +39,28 @@ START_STOP_DAEMON_ARGS=""
 
 # Check the user
 if [ -n "${USER}" ]; then
-	if ! getent passwd | grep -q "^${USER}:"; then
-		echo "$0: user for running <%= project_name %> doesn't exist: ${USER}" >&2
-		exit 1
-	fi
-	if [ ! -d $(dirname ${PIDFILE}) ]; then
-		mkdir -p $(dirname ${PIDFILE})
-	fi
-	chown -R ${USER} $(dirname ${PIDFILE})
-	START_STOP_DAEMON_ARGS="${START_STOP_DAEMON_ARGS} -c ${USER}"
+  if ! getent passwd | grep -q "^${USER}:"; then
+    echo "$0: user for running <%= project_name %> doesn't exist: ${USER}" >&2
+    exit 1
+  fi
+  if [ ! -d $(dirname ${PIDFILE}) ]; then
+    mkdir -p $(dirname ${PIDFILE})
+  fi
+  chown -R ${USER} $(dirname ${PIDFILE})
+  START_STOP_DAEMON_ARGS="${START_STOP_DAEMON_ARGS} -c ${USER}"
 fi
 if [ -n "${GROUP}" ]; then
-	if ! getent group | grep -q "^${GROUP}:"; then
-		echo "$0: group for running <%= project_name %> doesn't exist: ${GROUP}" >&2
-		exit 1
-	fi
-	START_STOP_DAEMON_ARGS="${START_STOP_DAEMON_ARGS} --group ${GROUP}"
+  if ! getent group | grep -q "^${GROUP}:"; then
+    echo "$0: group for running <%= project_name %> doesn't exist: ${GROUP}" >&2
+    exit 1
+  fi
+  START_STOP_DAEMON_ARGS="${START_STOP_DAEMON_ARGS} --group ${GROUP}"
 fi
 
 # 2012/04/17 Kazuki Ohta <k@treasure-data.com>
 # Use jemalloc to avoid memory fragmentation
 if [ -f "<%= File.join(root_path, install_path, "embedded/lib/libjemalloc.so") %>" ]; then
-	export LD_PRELOAD=<%= File.join(root_path, install_path, "embedded/lib/libjemalloc.so") %>
+  export LD_PRELOAD=<%= File.join(root_path, install_path, "embedded/lib/libjemalloc.so") %>
 fi
 
 #
@@ -68,23 +68,23 @@ fi
 #
 do_start()
 {
-	# Set Max number of file descriptors for the safety sake
-	# see http://docs.fluentd.org/en/articles/before-install
-	ulimit -n 65536
+  # Set Max number of file descriptors for the safety sake
+  # see http://docs.fluentd.org/en/articles/before-install
+  ulimit -n 65536
 
-	# Return
-	#   0 if daemon has been started
-	#   1 if daemon was already running
-	#   2 if daemon could not be started
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON \
-	${START_STOP_DAEMON_ARGS} --test > /dev/null \
-		|| return 1
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON \
-	${START_STOP_DAEMON_ARGS} -- $DAEMON_ARGS \
-		|| return 2
-	# Add code here, if necessary, that waits for the process to be ready
-	# to handle requests from services started subsequently which depend
-	# on this one.  As a last resort, sleep for some time.
+  # Return
+  #   0 if daemon has been started
+  #   1 if daemon was already running
+  #   2 if daemon could not be started
+  start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON \
+    ${START_STOP_DAEMON_ARGS} --test > /dev/null \
+    || return 1
+  start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON \
+    ${START_STOP_DAEMON_ARGS} -- $DAEMON_ARGS \
+    || return 2
+  # Add code here, if necessary, that waits for the process to be ready
+  # to handle requests from services started subsequently which depend
+  # on this one.  As a last resort, sleep for some time.
 }
 
 #
@@ -92,106 +92,106 @@ do_start()
 #
 do_stop()
 {
-	# Return
-	#   0 if daemon has been stopped
-	#   1 if daemon was already stopped
-	#   2 if daemon could not be stopped
-	#   other if a failure occurred
-	local RETVAL=0
-	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name ruby || RETVAL="$?"
-	[ "$RETVAL" = 2 ] && return 2
-	# Wait for children to finish too if this is a daemon that forks
-	# and if the daemon is only ever run from this initscript.
-	# If the above conditions are not satisfied then add some other code
-	# that waits for the process to drop all resources that could be
-	# needed by services started subsequently.  A last resort is to
-	# sleep for some time.
-	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON || RETVAL="$?"
-	[ "$RETVAL" = 2 ] && return 2
-	# Many daemons don't delete their pidfiles when they exit.
-	rm -f $PIDFILE
-	return "$RETVAL"
+  # Return
+  #   0 if daemon has been stopped
+  #   1 if daemon was already stopped
+  #   2 if daemon could not be stopped
+  #   other if a failure occurred
+  local RETVAL=0
+  start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name ruby || RETVAL="$?"
+  [ "$RETVAL" = 2 ] && return 2
+  # Wait for children to finish too if this is a daemon that forks
+  # and if the daemon is only ever run from this initscript.
+  # If the above conditions are not satisfied then add some other code
+  # that waits for the process to drop all resources that could be
+  # needed by services started subsequently.  A last resort is to
+  # sleep for some time.
+  start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON || RETVAL="$?"
+  [ "$RETVAL" = 2 ] && return 2
+  # Many daemons don't delete their pidfiles when they exit.
+  rm -f $PIDFILE
+  return "$RETVAL"
 }
 
 #
 # Function that sends a SIGHUP to the daemon/service
 #
 do_reload() {
-	#
-	# If the daemon can reload its configuration without
-	# restarting (for example, when it is sent a SIGHUP),
-	# then implement that here.
-	#
-	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name ruby
+  #
+  # If the daemon can reload its configuration without
+  # restarting (for example, when it is sent a SIGHUP),
+  # then implement that here.
+  #
+  start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name ruby
 }
 
 do_configtest() {
-	eval "$DAEMON_ARGS --user ${USER} --group ${GROUP} --dry-run -q"
+  eval "$DAEMON_ARGS --user ${USER} --group ${GROUP} --dry-run -q"
 }
 
 RETVAL=0
 case "$1" in
-  start)
-    log_daemon_msg "Starting $DESC " "$NAME"
+"start" )
+  log_daemon_msg "Starting $DESC " "$NAME"
+  do_start || RETVAL="$?"
+  case "$RETVAL" in
+  0 | 1 ) log_end_msg 0 ;;
+      2 ) log_end_msg 1 ;;
+  esac
+  ;;
+"stop" )
+  log_daemon_msg "Stopping $DESC" "$NAME"
+  do_stop || RETVAL="$?"
+  case "$RETVAL" in
+  0 | 1 ) log_end_msg 0 ;;
+      2 ) log_end_msg 1 ;;
+  esac
+  ;;
+"status" )
+  status_of_proc "$DAEMON" "$NAME"
+  ;;
+"reload" | "force-reload" )
+  #
+  # If do_reload() is not implemented then leave this commented out
+  # and leave 'force-reload' as an alias for 'restart'.
+  #
+  log_daemon_msg "Reloading $DESC" "$NAME"
+  do_configtest || log_end_msg 1
+  do_reload || RETVAL="$?"
+  log_end_msg "$RETVAL"
+  ;;
+"restart" | "force-reload" )
+  #
+  # If the "reload" option is implemented then remove the
+  # 'force-reload' alias
+  #
+  log_daemon_msg "Restarting $DESC" "$NAME"
+  do_configtest || log_end_msg 1
+  do_stop || RETVAL="$?"
+  case "$RETVAL" in
+  0 | 1 )
+    RETVAL=0
     do_start || RETVAL="$?"
     case "$RETVAL" in
-		0|1) log_end_msg 0 ;;
-		2) log_end_msg 1 ;;
-	esac
+    0 ) log_end_msg 0 ;;
+    1 ) log_end_msg 1 ;; # Old process is still running
+    * ) log_end_msg 1 ;; # Failed to start
+    esac
+    ;;
+  * )
+    # Failed to stop
+    log_end_msg 1
+    ;;
+  esac
   ;;
-  stop)
-	log_daemon_msg "Stopping $DESC" "$NAME"
-	do_stop || RETVAL="$?"
-	case "$RETVAL" in
-		0|1) log_end_msg 0 ;;
-		2) log_end_msg 1 ;;
-	esac
-	;;
-  status)
-       status_of_proc "$DAEMON" "$NAME"
-       ;;
-  reload|force-reload)
-	#
-	# If do_reload() is not implemented then leave this commented out
-	# and leave 'force-reload' as an alias for 'restart'.
-	#
-	log_daemon_msg "Reloading $DESC" "$NAME"
-	do_configtest || log_end_msg 1
-	do_reload || RETVAL="$?"
-	log_end_msg "$RETVAL"
-	;;
-  restart|force-reload)
-	#
-	# If the "reload" option is implemented then remove the
-	# 'force-reload' alias
-	#
-	log_daemon_msg "Restarting $DESC" "$NAME"
-	do_configtest || log_end_msg 1
-	do_stop || RETVAL="$?"
-	case "$RETVAL" in
-	  0|1)
-		RETVAL=0
-		do_start || RETVAL="$?"
-		case "$RETVAL" in
-			0) log_end_msg 0 ;;
-			1) log_end_msg 1 ;; # Old process is still running
-			*) log_end_msg 1 ;; # Failed to start
-		esac
-		;;
-	  *)
-	  	# Failed to stop
-		log_end_msg 1
-		;;
-	esac
-	;;
-  configtest)
-	do_configtest || RETVAL="$?"
-		log_end_msg "$RETVAL"
-	;;
-  *)
-	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload|configtest}" >&2
-	exit 3
-	;;
+"configtest" )
+  do_configtest || RETVAL="$?"
+  log_end_msg "$RETVAL"
+  ;;
+* )
+  echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload|configtest}" >&2
+  exit 3
+  ;;
 esac
 
 :
